theme: jekyll-theme-cayman

title: "Vivian Jerono Kipsang | Data Science Portfolio"

description: "Data Science and Analytics portfolio showcasing projects, technical skills, certifications, and hands-on challenges."
